apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluraymanagement
  labels:
    app: bluraymanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluraymanagement
  template:
    metadata:
      labels:
        app: bluraymanagement
    spec:
      containers:
        - name: bluraymanagement
          image: username/bluraymanagement:latest
          ports:
            - containerPort: 8080

