apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluraymanagement
  labels:
    app: bluraymanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluraymanagement
  template:
    metadata:
      labels:
        app: bluraymanagement
    spec:
      containers:
        - name: bluraymanagement
          image: username/bluraymanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
